FROM damireh/ruby2.7-node
ENV RAILS_ENV=development

WORKDIR /usr/src/app

COPY Gemfile* ./

RUN bundle config set --local without 'production'
RUN bundle install

RUN gem install rails -v '5.2.7' -V --no-document

# for db client
# doing exit 0 because apt throws warnings over oldstable version of debian
RUN apt update -y; exit 0
RUN apt install sqlite3 -y; exit 0

# Copy the main application.
COPY . ./



# Expose port 3000 to the Docker host, so we can access it
# from the outside.
EXPOSE 3000


#to avoid overwrites from volume bind with docker-compose, copy into root folder
COPY ./docker-entrypoint-rails.sh /tmp/run-docker-entrypoint.sh


RUN ["chmod", "+x", "/tmp/run-docker-entrypoint.sh"]

ENTRYPOINT ["/tmp/run-docker-entrypoint.sh"]