version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.07.1
      docker_layer_caching: true
    steps:
      - checkout
      - run: ./build_docker.sh
      - run: docker-compose up -d rails
      - run: docker-compose run --rm --entrypoint "cypress run --project ./" cypress_gui
